version: '3'

services:
  postgres1:
    image: postgres:latest
    environment:
      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:latest
    environment:
      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
